import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import { type Diagnosis, type User } from '../api';

export const generateHealthCertificate = async (history: Diagnosis[], user: User | null) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Colors
  const darkColor: [number, number, number] = [15, 23, 42]; // #0f172a

  // Helper functions
  const addHeader = () => {
    // Top Bar
    doc.setFillColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Logo Text
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('LeafGuard', margin, 25);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text('AI-POWERED PLANT HEALTH SYSTEMS', margin, 32);

    // Certificate Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('HEALTH CERTIFICATE', pageWidth - margin, 25, { align: 'right' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`ID: LG-CERT-${Math.floor(100000 + Math.random() * 900000)}`, pageWidth - margin, 32, { align: 'right' });
  };

  const addFooter = (pageNum: number) => {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('Generated by LeafGuard AI Diagnostics', margin, pageHeight - 10);
    const dateStr = new Date().toLocaleDateString('en-IN', { dateStyle: 'long' });
    doc.text(dateStr, pageWidth - margin, pageHeight - 10, { align: 'right' });
  };

  // --- PAGE 1: COVER ---
  addHeader();

  // Farmer Info Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, 50, pageWidth - (margin * 2), 40, 3, 3, 'F');
  
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('CERTIFICATE HOLDER', margin + 10, 62);
  
  doc.setFontSize(16);
  doc.text(user?.fullName || 'Valued Farmer', margin + 10, 72);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(user?.email || 'N/A', margin + 10, 80);

  // Summary Statistics
  const totalScans = history.length;
  const healthyScans = history.filter(d => d.isHealthy).length;
  const healthRate = totalScans > 0 ? Math.round((healthyScans / totalScans) * 100) : 0;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.text('CROP HEALTH SUMMARY', margin, 110);

  // Stats Grid
  const gridW = (pageWidth - (margin * 2) - 20) / 3;
  const gridY = 118;

  // Total Scans
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, gridY, gridW, 30, 2, 2, 'F');
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(8);
  doc.text('TOTAL ANALYSES', margin + gridW/2, gridY + 10, { align: 'center' });
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.setFontSize(14);
  doc.text(totalScans.toString(), margin + gridW/2, gridY + 22, { align: 'center' });

  // Healthy Scans
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(margin + gridW + 10, gridY, gridW, 30, 2, 2, 'F');
  doc.setTextColor(22, 101, 52);
  doc.setFontSize(8);
  doc.text('HEALTHY CASES', margin + gridW + 10 + gridW/2, gridY + 10, { align: 'center' });
  doc.setFontSize(14);
  doc.text(healthyScans.toString(), margin + gridW + 10 + gridW/2, gridY + 22, { align: 'center' });

  // Health Rate
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(margin + (gridW * 2) + 20, gridY, gridW, 30, 2, 2, 'F');
  doc.setTextColor(30, 64, 175);
  doc.setFontSize(8);
  doc.text('HEALTH INDEX', margin + (gridW * 2) + 20 + gridW/2, gridY + 10, { align: 'center' });
  doc.setFontSize(14);
  doc.text(`${healthRate}%`, margin + (gridW * 2) + 20 + gridW/2, gridY + 22, { align: 'center' });

  // Status Indicator
  let statusText = "IMPROVING";
  let statusColor: [number, number, number] = [22, 163, 74]; // green
  if (healthRate < 50) {
    statusText = "CRITICAL";
    statusColor = [220, 38, 38]; // red
  } else if (healthRate < 80) {
    statusText = "STABLE";
    statusColor = [217, 119, 6]; // amber
  }

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('OVERALL HEALTH CLASSIFICATION', margin, 165);
  
  doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.roundedRect(margin, 170, 50, 10, 1, 1, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text(statusText, margin + 25, 177, { align: 'center' });

  // Verification Seal (Primitive representation)
  const sealX = pageWidth - margin - 40;
  const sealY = 220;
  doc.setDrawColor(22, 163, 74);
  doc.setLineWidth(1);
  doc.circle(sealX + 20, sealY + 20, 20, 'S');
  doc.circle(sealX + 20, sealY + 20, 18, 'S');
  doc.setFontSize(6);
  doc.setTextColor(22, 163, 74);
  doc.text('VERIFIED BY LEAFGUARD AI', sealX + 20, sealY + 15, { align: 'center' });
  doc.text('OFFICIAL DOCUMENT', sealX + 20, sealY + 25, { align: 'center' });
  doc.setFontSize(8);
  doc.text('2026', sealX + 20, sealY + 32, { align: 'center' });

  addFooter(1);

  // --- PAGE 2: DIAGNOSIS HISTORY ---
  doc.addPage();
  addHeader();

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.text('DETAILED DIAGNOSIS LOG', margin, 55);

  autoTable(doc, {
    startY: 60,
    head: [['DATE', 'DIAGNOSIS', 'CONFIDENCE', 'STATUS']],
    body: history.map(item => [
      new Date(item.timestamp).toLocaleDateString(),
      item.diseaseName,
      `${Math.round(item.confidence)}%`,
      item.isHealthy ? 'HEALTHY' : 'DISEASED'
    ]),
    headStyles: {
      fillColor: darkColor,
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [71, 85, 105]
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    margin: { left: margin, right: margin }
  });

  // Trend Chart (Simplified Bar Chart)
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  if (finalY < 230) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('HEALTH TREND ANALYSIS (Last 10 Scans)', margin, finalY + 20);
    
    const chartX = margin;
    const chartY = finalY + 60;
    const chartW = pageWidth - (margin * 2);
    const chartH = 30;

    // Baseline
    doc.setDrawColor(203, 213, 225);
    doc.line(chartX, chartY, chartX + chartW, chartY);

    // Bars
    const recentHistory = history.slice(0, 10).reverse();
    const barW = (chartW / 10) - 4;
    
    recentHistory.forEach((item, i) => {
      const barX = chartX + (i * (chartW / 10)) + 2;
      const barH = (item.confidence / 100) * chartH;
      const color: [number, number, number] = item.isHealthy ? [22, 163, 74] : [220, 38, 38];
      const lightColor: [number, number, number] = item.isHealthy ? [220, 252, 231] : [254, 226, 226];
      
      doc.setFillColor(lightColor[0], lightColor[1], lightColor[2]);
      doc.rect(barX, chartY - barH, barW, barH, 'F');
      
      doc.setFillColor(color[0], color[1], color[2]);
      doc.rect(barX, chartY - 2, barW, 2, 'F');
    });

    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text('Sequence of Analyses', chartX + chartW/2, chartY + 10, { align: 'center' });
  }

  addFooter(2);

  // --- PAGE 3: COMPLIANCE ---
  doc.addPage();
  addHeader();

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('LEGAL COMPLIANCE & TERMS', margin, 55);

  const terms = [
    "1. This certificate is generated based on AI analysis of user-submitted images.",
    "2. LeafGuard does not guarantee 100% accuracy and should be used as a supporting tool.",
    "3. Export agencies and insurance providers are advised to verify the timestamped digital signature.",
    "4. All diagnostic data is encrypted and stored in compliance with agricultural data standards.",
    "5. For critical export batches, secondary physical inspection by a certified agronomist is recommended."
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  let termY = 65;
  terms.forEach(term => {
    const lines = doc.splitTextToSize(term, pageWidth - (margin * 2));
    doc.text(lines, margin, termY);
    termY += (lines.length * 5) + 2;
  });

  // Signatures
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.text('AUTHORIZED BY', margin, 180);
  doc.line(margin, 205, margin + 60, 205);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('LeafGuard AI Verification Systems', margin, 210);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('HOLDER SIGNATURE', pageWidth - margin - 60, 180);
  doc.line(pageWidth - margin - 60, 205, pageWidth - margin, 205);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(user?.fullName || 'Farmer Signature', pageWidth - margin - 60, 210);

  addFooter(3);

  doc.save(`LeafGuard_Health_Certificate_${user?.fullName?.replace(/\s/g, '_') || 'Farmer'}.pdf`);
};
